spring.application.name=mentalhealth

server.port=8081
server.servlet.context-path=/

spring.datasource.url=jdbc:postgresql://localhost:5432/mentalhealth
spring.datasource.username=postgres
spring.datasource.password=3625
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ollama server
langchain4j.ollama.chat-model.base-url=http://localhost:11434

# Model đang chạy trên Ollama
langchain4j.ollama.chat-model.model-name=qwen3.5:4b

# Mức độ sáng tạo của model
langchain4j.ollama.chat-model.temperature=0.7

# Timeout
langchain4j.ollama.chat-model.timeout=PT10M

mentalhealth.app.jwtSecret=iAquaUIgXtAcrIYDXjMen6OOpGxXBEmyXsVl53QRAHM=
mentalhealth.app.jwtExpirationMs=86400000